Fix typo causing examples to fail
app_identifer is missing the last i, it should be app_identifier.
Causes the following error:
    TypeError: init_themes() got an unexpected keyword argument 'app_identifer'